---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft

resources:
  - service-account.yaml
  - statefulset.yaml
  - service.yaml
  - ingress-route.yaml

configMapGenerator:
  - name: vanilla-server-files
    files:
      - server.properties
      - eula.txt
  - name: vanilla-jvm-files
    files:
      - user_jvm_args.txt

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: minecraft
  type: vanilla
  mods: "false"
  version: "1.19.x"
