---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: vanilla

spec:
  selector:
    matchLabels:
      minecraft: vanilla
  serviceName: vanilla
  replicas: 1
  template:
    metadata:
      labels:
        minecraft: vanilla
    spec:
      serviceAccountName: minecraft
      initContainers:
        - name: setup
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - "-c"
            - |
              set -xe
              find /setup /config /data -print
              cp -rav /setup/* /data
          volumeMounts:
            - name: vanilla-data
              mountPath: /data
            - name: server-files
              mountPath: /setup
            - name: jvm-files
              mountPath: /config
      containers:
        - name: minecraft
          image: ghcr.io/schifferers/minecraft:vanilla
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              name: minecraft
          volumeMounts:
            - name: vanilla-data
              mountPath: /data
            - name: jvm-files
              mountPath: /config
      volumes:
        - name: server-files
          configMap:
            name: vanilla-server-files
        - name: jvm-files
          configMap:
            name: vanilla-jvm-files
  volumeClaimTemplates:
    - metadata:
        name: vanilla-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
