apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: ghcr

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .registry | toString }}"
    name: ghcr
    creationPolicy: Owner
  data:
    - secretKey: registry
      remoteRef:
        key: Registry
